#!/bin/bash -x
# bu - BackUp
# Backup any file to a folder on the desktop

# Author: Daniel Mwaba Mwale
# E-mail: daniel.mwale@zamtel.co.zm
# Date: Sunday, 25th February, 2018; 10:58AM
# Version: 1
#
# Format: bu [file]
# Example: bu /directory/file
#		   This will produce a copy of /directory/file in a desktop folder

function backup_file() {
		if [ -f "$1" ]
		then
				local BACKUP_FILE="/home/mexen/Desktop/miscbu/$(basename ${1}).$(date +%F).$$"
				echo "Backing up $1 to ${BACKUP_FILE}"
				cp $1 $BACKUP_FILE
				if [ $? -eq "0" ]
				then
						echo "Backup succeeded!"
						# exit 0
						return 0
				else
						echo "Backup failed!"
						# exit 1
						return 1
				fi
		else
				echo "Backup failed!"
				exit 1
				# return 1
		fi
}

backup_file $1
